version: "3"
services:
  app:
    container_name: auth-app-nodejs
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - PORT=${PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - DB=${DB}
      - MONGO_URL=mongodb://db:27017
    ports:
      - 3000:3000

  db:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "{ ping: 1 }"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
    #   - MONGO_INITDB_ROOT_USERNAME=username
    #   - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=${DB}
