version: "3.7"
services:
  app:
    container_name: auth-app-nodejs
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    command: ["node", "server.js"]
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - PORT=${PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - DB=${DB}
      - MONGO_URL=mongodb:27017
    ports:
      - 3000:3000

  db:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /data/data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "{ ping: 1 }"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db
networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254